version: '3'
services:
  spring-app:
    links:
      - liquibase
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  currency-db-host:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=currency-db'
      - 'POSTGRES_PASSWORD=topsecret'
      - 'POSTGRES_USER=appuser'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5

  liquibase:
    image: 'liquibase/liquibase:latest'
    container_name: Liquibase_container
    depends_on:
      currency-db-host:
        condition: service_healthy
    volumes:
      - ./liquibase/changelog/:/liquibase/changelog/
    command: --defaults-file=/liquibase/changelog/liquibase.properties update
